# UART
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_CONSOLE=n
CONFIG_CONSOLE=n
CONFIG_PRINTK=n
CONFIG_BOOT_BANNER=n

# GPIO
CONFIG_GPIO=y

# ADC (IN1/IN2/BTN analog input)
CONFIG_ADC=y

# PWM (sound)
CONFIG_PWM=y

# Flash / NVS storage
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y

# I2C
CONFIG_I2C=y

# SPI (LPSPI0 for NTSC pixel output on FRDM-MCXA153)
CONFIG_SPI=y

# Threads
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_MAIN_THREAD_PRIORITY=7
CONFIG_HEAP_MEM_POOL_SIZE=4096
